// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openbao/openbao-plugins/secrets/aws (interfaces: IAMAPI)
//
// Generated by this command:
//
//	mockgen -typed -destination=internal/mock/iam.go . IAMAPI
//

// Package mock_aws is a generated GoMock package.
package mock_aws

import (
	context "context"
	reflect "reflect"

	iam "github.com/aws/aws-sdk-go-v2/service/iam"
	gomock "go.uber.org/mock/gomock"
)

// MockIAMAPI is a mock of IAMAPI interface.
type MockIAMAPI struct {
	ctrl     *gomock.Controller
	recorder *MockIAMAPIMockRecorder
	isgomock struct{}
}

// MockIAMAPIMockRecorder is the mock recorder for MockIAMAPI.
type MockIAMAPIMockRecorder struct {
	mock *MockIAMAPI
}

// NewMockIAMAPI creates a new mock instance.
func NewMockIAMAPI(ctrl *gomock.Controller) *MockIAMAPI {
	mock := &MockIAMAPI{ctrl: ctrl}
	mock.recorder = &MockIAMAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAMAPI) EXPECT() *MockIAMAPIMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockIAMAPI) AddUserToGroup(ctx context.Context, params *iam.AddUserToGroupInput, optFns ...func(*iam.Options)) (*iam.AddUserToGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddUserToGroup", varargs...)
	ret0, _ := ret[0].(*iam.AddUserToGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockIAMAPIMockRecorder) AddUserToGroup(ctx, params any, optFns ...any) *MockIAMAPIAddUserToGroupCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockIAMAPI)(nil).AddUserToGroup), varargs...)
	return &MockIAMAPIAddUserToGroupCall{Call: call}
}

// MockIAMAPIAddUserToGroupCall wrap *gomock.Call
type MockIAMAPIAddUserToGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIAddUserToGroupCall) Return(arg0 *iam.AddUserToGroupOutput, arg1 error) *MockIAMAPIAddUserToGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIAddUserToGroupCall) Do(f func(context.Context, *iam.AddUserToGroupInput, ...func(*iam.Options)) (*iam.AddUserToGroupOutput, error)) *MockIAMAPIAddUserToGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIAddUserToGroupCall) DoAndReturn(f func(context.Context, *iam.AddUserToGroupInput, ...func(*iam.Options)) (*iam.AddUserToGroupOutput, error)) *MockIAMAPIAddUserToGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AttachUserPolicy mocks base method.
func (m *MockIAMAPI) AttachUserPolicy(ctx context.Context, params *iam.AttachUserPolicyInput, optFns ...func(*iam.Options)) (*iam.AttachUserPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AttachUserPolicy", varargs...)
	ret0, _ := ret[0].(*iam.AttachUserPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AttachUserPolicy indicates an expected call of AttachUserPolicy.
func (mr *MockIAMAPIMockRecorder) AttachUserPolicy(ctx, params any, optFns ...any) *MockIAMAPIAttachUserPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachUserPolicy", reflect.TypeOf((*MockIAMAPI)(nil).AttachUserPolicy), varargs...)
	return &MockIAMAPIAttachUserPolicyCall{Call: call}
}

// MockIAMAPIAttachUserPolicyCall wrap *gomock.Call
type MockIAMAPIAttachUserPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIAttachUserPolicyCall) Return(arg0 *iam.AttachUserPolicyOutput, arg1 error) *MockIAMAPIAttachUserPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIAttachUserPolicyCall) Do(f func(context.Context, *iam.AttachUserPolicyInput, ...func(*iam.Options)) (*iam.AttachUserPolicyOutput, error)) *MockIAMAPIAttachUserPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIAttachUserPolicyCall) DoAndReturn(f func(context.Context, *iam.AttachUserPolicyInput, ...func(*iam.Options)) (*iam.AttachUserPolicyOutput, error)) *MockIAMAPIAttachUserPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateAccessKey mocks base method.
func (m *MockIAMAPI) CreateAccessKey(ctx context.Context, params *iam.CreateAccessKeyInput, optFns ...func(*iam.Options)) (*iam.CreateAccessKeyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateAccessKey", varargs...)
	ret0, _ := ret[0].(*iam.CreateAccessKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessKey indicates an expected call of CreateAccessKey.
func (mr *MockIAMAPIMockRecorder) CreateAccessKey(ctx, params any, optFns ...any) *MockIAMAPICreateAccessKeyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessKey", reflect.TypeOf((*MockIAMAPI)(nil).CreateAccessKey), varargs...)
	return &MockIAMAPICreateAccessKeyCall{Call: call}
}

// MockIAMAPICreateAccessKeyCall wrap *gomock.Call
type MockIAMAPICreateAccessKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPICreateAccessKeyCall) Return(arg0 *iam.CreateAccessKeyOutput, arg1 error) *MockIAMAPICreateAccessKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPICreateAccessKeyCall) Do(f func(context.Context, *iam.CreateAccessKeyInput, ...func(*iam.Options)) (*iam.CreateAccessKeyOutput, error)) *MockIAMAPICreateAccessKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPICreateAccessKeyCall) DoAndReturn(f func(context.Context, *iam.CreateAccessKeyInput, ...func(*iam.Options)) (*iam.CreateAccessKeyOutput, error)) *MockIAMAPICreateAccessKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateUser mocks base method.
func (m *MockIAMAPI) CreateUser(ctx context.Context, params *iam.CreateUserInput, optFns ...func(*iam.Options)) (*iam.CreateUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateUser", varargs...)
	ret0, _ := ret[0].(*iam.CreateUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIAMAPIMockRecorder) CreateUser(ctx, params any, optFns ...any) *MockIAMAPICreateUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIAMAPI)(nil).CreateUser), varargs...)
	return &MockIAMAPICreateUserCall{Call: call}
}

// MockIAMAPICreateUserCall wrap *gomock.Call
type MockIAMAPICreateUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPICreateUserCall) Return(arg0 *iam.CreateUserOutput, arg1 error) *MockIAMAPICreateUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPICreateUserCall) Do(f func(context.Context, *iam.CreateUserInput, ...func(*iam.Options)) (*iam.CreateUserOutput, error)) *MockIAMAPICreateUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPICreateUserCall) DoAndReturn(f func(context.Context, *iam.CreateUserInput, ...func(*iam.Options)) (*iam.CreateUserOutput, error)) *MockIAMAPICreateUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteAccessKey mocks base method.
func (m *MockIAMAPI) DeleteAccessKey(ctx context.Context, params *iam.DeleteAccessKeyInput, optFns ...func(*iam.Options)) (*iam.DeleteAccessKeyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAccessKey", varargs...)
	ret0, _ := ret[0].(*iam.DeleteAccessKeyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAccessKey indicates an expected call of DeleteAccessKey.
func (mr *MockIAMAPIMockRecorder) DeleteAccessKey(ctx, params any, optFns ...any) *MockIAMAPIDeleteAccessKeyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessKey", reflect.TypeOf((*MockIAMAPI)(nil).DeleteAccessKey), varargs...)
	return &MockIAMAPIDeleteAccessKeyCall{Call: call}
}

// MockIAMAPIDeleteAccessKeyCall wrap *gomock.Call
type MockIAMAPIDeleteAccessKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIDeleteAccessKeyCall) Return(arg0 *iam.DeleteAccessKeyOutput, arg1 error) *MockIAMAPIDeleteAccessKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIDeleteAccessKeyCall) Do(f func(context.Context, *iam.DeleteAccessKeyInput, ...func(*iam.Options)) (*iam.DeleteAccessKeyOutput, error)) *MockIAMAPIDeleteAccessKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIDeleteAccessKeyCall) DoAndReturn(f func(context.Context, *iam.DeleteAccessKeyInput, ...func(*iam.Options)) (*iam.DeleteAccessKeyOutput, error)) *MockIAMAPIDeleteAccessKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUser mocks base method.
func (m *MockIAMAPI) DeleteUser(ctx context.Context, params *iam.DeleteUserInput, optFns ...func(*iam.Options)) (*iam.DeleteUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteUser", varargs...)
	ret0, _ := ret[0].(*iam.DeleteUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockIAMAPIMockRecorder) DeleteUser(ctx, params any, optFns ...any) *MockIAMAPIDeleteUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockIAMAPI)(nil).DeleteUser), varargs...)
	return &MockIAMAPIDeleteUserCall{Call: call}
}

// MockIAMAPIDeleteUserCall wrap *gomock.Call
type MockIAMAPIDeleteUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIDeleteUserCall) Return(arg0 *iam.DeleteUserOutput, arg1 error) *MockIAMAPIDeleteUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIDeleteUserCall) Do(f func(context.Context, *iam.DeleteUserInput, ...func(*iam.Options)) (*iam.DeleteUserOutput, error)) *MockIAMAPIDeleteUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIDeleteUserCall) DoAndReturn(f func(context.Context, *iam.DeleteUserInput, ...func(*iam.Options)) (*iam.DeleteUserOutput, error)) *MockIAMAPIDeleteUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DeleteUserPolicy mocks base method.
func (m *MockIAMAPI) DeleteUserPolicy(ctx context.Context, params *iam.DeleteUserPolicyInput, optFns ...func(*iam.Options)) (*iam.DeleteUserPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteUserPolicy", varargs...)
	ret0, _ := ret[0].(*iam.DeleteUserPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserPolicy indicates an expected call of DeleteUserPolicy.
func (mr *MockIAMAPIMockRecorder) DeleteUserPolicy(ctx, params any, optFns ...any) *MockIAMAPIDeleteUserPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserPolicy", reflect.TypeOf((*MockIAMAPI)(nil).DeleteUserPolicy), varargs...)
	return &MockIAMAPIDeleteUserPolicyCall{Call: call}
}

// MockIAMAPIDeleteUserPolicyCall wrap *gomock.Call
type MockIAMAPIDeleteUserPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIDeleteUserPolicyCall) Return(arg0 *iam.DeleteUserPolicyOutput, arg1 error) *MockIAMAPIDeleteUserPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIDeleteUserPolicyCall) Do(f func(context.Context, *iam.DeleteUserPolicyInput, ...func(*iam.Options)) (*iam.DeleteUserPolicyOutput, error)) *MockIAMAPIDeleteUserPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIDeleteUserPolicyCall) DoAndReturn(f func(context.Context, *iam.DeleteUserPolicyInput, ...func(*iam.Options)) (*iam.DeleteUserPolicyOutput, error)) *MockIAMAPIDeleteUserPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DetachUserPolicy mocks base method.
func (m *MockIAMAPI) DetachUserPolicy(ctx context.Context, params *iam.DetachUserPolicyInput, optFns ...func(*iam.Options)) (*iam.DetachUserPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DetachUserPolicy", varargs...)
	ret0, _ := ret[0].(*iam.DetachUserPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetachUserPolicy indicates an expected call of DetachUserPolicy.
func (mr *MockIAMAPIMockRecorder) DetachUserPolicy(ctx, params any, optFns ...any) *MockIAMAPIDetachUserPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachUserPolicy", reflect.TypeOf((*MockIAMAPI)(nil).DetachUserPolicy), varargs...)
	return &MockIAMAPIDetachUserPolicyCall{Call: call}
}

// MockIAMAPIDetachUserPolicyCall wrap *gomock.Call
type MockIAMAPIDetachUserPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIDetachUserPolicyCall) Return(arg0 *iam.DetachUserPolicyOutput, arg1 error) *MockIAMAPIDetachUserPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIDetachUserPolicyCall) Do(f func(context.Context, *iam.DetachUserPolicyInput, ...func(*iam.Options)) (*iam.DetachUserPolicyOutput, error)) *MockIAMAPIDetachUserPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIDetachUserPolicyCall) DoAndReturn(f func(context.Context, *iam.DetachUserPolicyInput, ...func(*iam.Options)) (*iam.DetachUserPolicyOutput, error)) *MockIAMAPIDetachUserPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetGroupPolicy mocks base method.
func (m *MockIAMAPI) GetGroupPolicy(ctx context.Context, params *iam.GetGroupPolicyInput, optFns ...func(*iam.Options)) (*iam.GetGroupPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetGroupPolicy", varargs...)
	ret0, _ := ret[0].(*iam.GetGroupPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupPolicy indicates an expected call of GetGroupPolicy.
func (mr *MockIAMAPIMockRecorder) GetGroupPolicy(ctx, params any, optFns ...any) *MockIAMAPIGetGroupPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupPolicy", reflect.TypeOf((*MockIAMAPI)(nil).GetGroupPolicy), varargs...)
	return &MockIAMAPIGetGroupPolicyCall{Call: call}
}

// MockIAMAPIGetGroupPolicyCall wrap *gomock.Call
type MockIAMAPIGetGroupPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIGetGroupPolicyCall) Return(arg0 *iam.GetGroupPolicyOutput, arg1 error) *MockIAMAPIGetGroupPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIGetGroupPolicyCall) Do(f func(context.Context, *iam.GetGroupPolicyInput, ...func(*iam.Options)) (*iam.GetGroupPolicyOutput, error)) *MockIAMAPIGetGroupPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIGetGroupPolicyCall) DoAndReturn(f func(context.Context, *iam.GetGroupPolicyInput, ...func(*iam.Options)) (*iam.GetGroupPolicyOutput, error)) *MockIAMAPIGetGroupPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUser mocks base method.
func (m *MockIAMAPI) GetUser(ctx context.Context, params *iam.GetUserInput, optFns ...func(*iam.Options)) (*iam.GetUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*iam.GetUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIAMAPIMockRecorder) GetUser(ctx, params any, optFns ...any) *MockIAMAPIGetUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIAMAPI)(nil).GetUser), varargs...)
	return &MockIAMAPIGetUserCall{Call: call}
}

// MockIAMAPIGetUserCall wrap *gomock.Call
type MockIAMAPIGetUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIGetUserCall) Return(arg0 *iam.GetUserOutput, arg1 error) *MockIAMAPIGetUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIGetUserCall) Do(f func(context.Context, *iam.GetUserInput, ...func(*iam.Options)) (*iam.GetUserOutput, error)) *MockIAMAPIGetUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIGetUserCall) DoAndReturn(f func(context.Context, *iam.GetUserInput, ...func(*iam.Options)) (*iam.GetUserOutput, error)) *MockIAMAPIGetUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAccessKeys mocks base method.
func (m *MockIAMAPI) ListAccessKeys(ctx context.Context, params *iam.ListAccessKeysInput, optFns ...func(*iam.Options)) (*iam.ListAccessKeysOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAccessKeys", varargs...)
	ret0, _ := ret[0].(*iam.ListAccessKeysOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessKeys indicates an expected call of ListAccessKeys.
func (mr *MockIAMAPIMockRecorder) ListAccessKeys(ctx, params any, optFns ...any) *MockIAMAPIListAccessKeysCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessKeys", reflect.TypeOf((*MockIAMAPI)(nil).ListAccessKeys), varargs...)
	return &MockIAMAPIListAccessKeysCall{Call: call}
}

// MockIAMAPIListAccessKeysCall wrap *gomock.Call
type MockIAMAPIListAccessKeysCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIListAccessKeysCall) Return(arg0 *iam.ListAccessKeysOutput, arg1 error) *MockIAMAPIListAccessKeysCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIListAccessKeysCall) Do(f func(context.Context, *iam.ListAccessKeysInput, ...func(*iam.Options)) (*iam.ListAccessKeysOutput, error)) *MockIAMAPIListAccessKeysCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIListAccessKeysCall) DoAndReturn(f func(context.Context, *iam.ListAccessKeysInput, ...func(*iam.Options)) (*iam.ListAccessKeysOutput, error)) *MockIAMAPIListAccessKeysCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAttachedGroupPolicies mocks base method.
func (m *MockIAMAPI) ListAttachedGroupPolicies(ctx context.Context, params *iam.ListAttachedGroupPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListAttachedGroupPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAttachedGroupPolicies", varargs...)
	ret0, _ := ret[0].(*iam.ListAttachedGroupPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachedGroupPolicies indicates an expected call of ListAttachedGroupPolicies.
func (mr *MockIAMAPIMockRecorder) ListAttachedGroupPolicies(ctx, params any, optFns ...any) *MockIAMAPIListAttachedGroupPoliciesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachedGroupPolicies", reflect.TypeOf((*MockIAMAPI)(nil).ListAttachedGroupPolicies), varargs...)
	return &MockIAMAPIListAttachedGroupPoliciesCall{Call: call}
}

// MockIAMAPIListAttachedGroupPoliciesCall wrap *gomock.Call
type MockIAMAPIListAttachedGroupPoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIListAttachedGroupPoliciesCall) Return(arg0 *iam.ListAttachedGroupPoliciesOutput, arg1 error) *MockIAMAPIListAttachedGroupPoliciesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIListAttachedGroupPoliciesCall) Do(f func(context.Context, *iam.ListAttachedGroupPoliciesInput, ...func(*iam.Options)) (*iam.ListAttachedGroupPoliciesOutput, error)) *MockIAMAPIListAttachedGroupPoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIListAttachedGroupPoliciesCall) DoAndReturn(f func(context.Context, *iam.ListAttachedGroupPoliciesInput, ...func(*iam.Options)) (*iam.ListAttachedGroupPoliciesOutput, error)) *MockIAMAPIListAttachedGroupPoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAttachedUserPolicies mocks base method.
func (m *MockIAMAPI) ListAttachedUserPolicies(ctx context.Context, params *iam.ListAttachedUserPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListAttachedUserPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAttachedUserPolicies", varargs...)
	ret0, _ := ret[0].(*iam.ListAttachedUserPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachedUserPolicies indicates an expected call of ListAttachedUserPolicies.
func (mr *MockIAMAPIMockRecorder) ListAttachedUserPolicies(ctx, params any, optFns ...any) *MockIAMAPIListAttachedUserPoliciesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachedUserPolicies", reflect.TypeOf((*MockIAMAPI)(nil).ListAttachedUserPolicies), varargs...)
	return &MockIAMAPIListAttachedUserPoliciesCall{Call: call}
}

// MockIAMAPIListAttachedUserPoliciesCall wrap *gomock.Call
type MockIAMAPIListAttachedUserPoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIListAttachedUserPoliciesCall) Return(arg0 *iam.ListAttachedUserPoliciesOutput, arg1 error) *MockIAMAPIListAttachedUserPoliciesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIListAttachedUserPoliciesCall) Do(f func(context.Context, *iam.ListAttachedUserPoliciesInput, ...func(*iam.Options)) (*iam.ListAttachedUserPoliciesOutput, error)) *MockIAMAPIListAttachedUserPoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIListAttachedUserPoliciesCall) DoAndReturn(f func(context.Context, *iam.ListAttachedUserPoliciesInput, ...func(*iam.Options)) (*iam.ListAttachedUserPoliciesOutput, error)) *MockIAMAPIListAttachedUserPoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroupPolicies mocks base method.
func (m *MockIAMAPI) ListGroupPolicies(ctx context.Context, params *iam.ListGroupPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListGroupPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListGroupPolicies", varargs...)
	ret0, _ := ret[0].(*iam.ListGroupPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupPolicies indicates an expected call of ListGroupPolicies.
func (mr *MockIAMAPIMockRecorder) ListGroupPolicies(ctx, params any, optFns ...any) *MockIAMAPIListGroupPoliciesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupPolicies", reflect.TypeOf((*MockIAMAPI)(nil).ListGroupPolicies), varargs...)
	return &MockIAMAPIListGroupPoliciesCall{Call: call}
}

// MockIAMAPIListGroupPoliciesCall wrap *gomock.Call
type MockIAMAPIListGroupPoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIListGroupPoliciesCall) Return(arg0 *iam.ListGroupPoliciesOutput, arg1 error) *MockIAMAPIListGroupPoliciesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIListGroupPoliciesCall) Do(f func(context.Context, *iam.ListGroupPoliciesInput, ...func(*iam.Options)) (*iam.ListGroupPoliciesOutput, error)) *MockIAMAPIListGroupPoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIListGroupPoliciesCall) DoAndReturn(f func(context.Context, *iam.ListGroupPoliciesInput, ...func(*iam.Options)) (*iam.ListGroupPoliciesOutput, error)) *MockIAMAPIListGroupPoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListGroupsForUser mocks base method.
func (m *MockIAMAPI) ListGroupsForUser(ctx context.Context, params *iam.ListGroupsForUserInput, optFns ...func(*iam.Options)) (*iam.ListGroupsForUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListGroupsForUser", varargs...)
	ret0, _ := ret[0].(*iam.ListGroupsForUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroupsForUser indicates an expected call of ListGroupsForUser.
func (mr *MockIAMAPIMockRecorder) ListGroupsForUser(ctx, params any, optFns ...any) *MockIAMAPIListGroupsForUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroupsForUser", reflect.TypeOf((*MockIAMAPI)(nil).ListGroupsForUser), varargs...)
	return &MockIAMAPIListGroupsForUserCall{Call: call}
}

// MockIAMAPIListGroupsForUserCall wrap *gomock.Call
type MockIAMAPIListGroupsForUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIListGroupsForUserCall) Return(arg0 *iam.ListGroupsForUserOutput, arg1 error) *MockIAMAPIListGroupsForUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIListGroupsForUserCall) Do(f func(context.Context, *iam.ListGroupsForUserInput, ...func(*iam.Options)) (*iam.ListGroupsForUserOutput, error)) *MockIAMAPIListGroupsForUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIListGroupsForUserCall) DoAndReturn(f func(context.Context, *iam.ListGroupsForUserInput, ...func(*iam.Options)) (*iam.ListGroupsForUserOutput, error)) *MockIAMAPIListGroupsForUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListUserPolicies mocks base method.
func (m *MockIAMAPI) ListUserPolicies(ctx context.Context, params *iam.ListUserPoliciesInput, optFns ...func(*iam.Options)) (*iam.ListUserPoliciesOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListUserPolicies", varargs...)
	ret0, _ := ret[0].(*iam.ListUserPoliciesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserPolicies indicates an expected call of ListUserPolicies.
func (mr *MockIAMAPIMockRecorder) ListUserPolicies(ctx, params any, optFns ...any) *MockIAMAPIListUserPoliciesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserPolicies", reflect.TypeOf((*MockIAMAPI)(nil).ListUserPolicies), varargs...)
	return &MockIAMAPIListUserPoliciesCall{Call: call}
}

// MockIAMAPIListUserPoliciesCall wrap *gomock.Call
type MockIAMAPIListUserPoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIListUserPoliciesCall) Return(arg0 *iam.ListUserPoliciesOutput, arg1 error) *MockIAMAPIListUserPoliciesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIListUserPoliciesCall) Do(f func(context.Context, *iam.ListUserPoliciesInput, ...func(*iam.Options)) (*iam.ListUserPoliciesOutput, error)) *MockIAMAPIListUserPoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIListUserPoliciesCall) DoAndReturn(f func(context.Context, *iam.ListUserPoliciesInput, ...func(*iam.Options)) (*iam.ListUserPoliciesOutput, error)) *MockIAMAPIListUserPoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PutUserPolicy mocks base method.
func (m *MockIAMAPI) PutUserPolicy(ctx context.Context, params *iam.PutUserPolicyInput, optFns ...func(*iam.Options)) (*iam.PutUserPolicyOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutUserPolicy", varargs...)
	ret0, _ := ret[0].(*iam.PutUserPolicyOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutUserPolicy indicates an expected call of PutUserPolicy.
func (mr *MockIAMAPIMockRecorder) PutUserPolicy(ctx, params any, optFns ...any) *MockIAMAPIPutUserPolicyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutUserPolicy", reflect.TypeOf((*MockIAMAPI)(nil).PutUserPolicy), varargs...)
	return &MockIAMAPIPutUserPolicyCall{Call: call}
}

// MockIAMAPIPutUserPolicyCall wrap *gomock.Call
type MockIAMAPIPutUserPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIPutUserPolicyCall) Return(arg0 *iam.PutUserPolicyOutput, arg1 error) *MockIAMAPIPutUserPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIPutUserPolicyCall) Do(f func(context.Context, *iam.PutUserPolicyInput, ...func(*iam.Options)) (*iam.PutUserPolicyOutput, error)) *MockIAMAPIPutUserPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIPutUserPolicyCall) DoAndReturn(f func(context.Context, *iam.PutUserPolicyInput, ...func(*iam.Options)) (*iam.PutUserPolicyOutput, error)) *MockIAMAPIPutUserPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveUserFromGroup mocks base method.
func (m *MockIAMAPI) RemoveUserFromGroup(ctx context.Context, params *iam.RemoveUserFromGroupInput, optFns ...func(*iam.Options)) (*iam.RemoveUserFromGroupOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveUserFromGroup", varargs...)
	ret0, _ := ret[0].(*iam.RemoveUserFromGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserFromGroup indicates an expected call of RemoveUserFromGroup.
func (mr *MockIAMAPIMockRecorder) RemoveUserFromGroup(ctx, params any, optFns ...any) *MockIAMAPIRemoveUserFromGroupCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromGroup", reflect.TypeOf((*MockIAMAPI)(nil).RemoveUserFromGroup), varargs...)
	return &MockIAMAPIRemoveUserFromGroupCall{Call: call}
}

// MockIAMAPIRemoveUserFromGroupCall wrap *gomock.Call
type MockIAMAPIRemoveUserFromGroupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPIRemoveUserFromGroupCall) Return(arg0 *iam.RemoveUserFromGroupOutput, arg1 error) *MockIAMAPIRemoveUserFromGroupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPIRemoveUserFromGroupCall) Do(f func(context.Context, *iam.RemoveUserFromGroupInput, ...func(*iam.Options)) (*iam.RemoveUserFromGroupOutput, error)) *MockIAMAPIRemoveUserFromGroupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPIRemoveUserFromGroupCall) DoAndReturn(f func(context.Context, *iam.RemoveUserFromGroupInput, ...func(*iam.Options)) (*iam.RemoveUserFromGroupOutput, error)) *MockIAMAPIRemoveUserFromGroupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TagUser mocks base method.
func (m *MockIAMAPI) TagUser(ctx context.Context, params *iam.TagUserInput, optFns ...func(*iam.Options)) (*iam.TagUserOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TagUser", varargs...)
	ret0, _ := ret[0].(*iam.TagUserOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagUser indicates an expected call of TagUser.
func (mr *MockIAMAPIMockRecorder) TagUser(ctx, params any, optFns ...any) *MockIAMAPITagUserCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagUser", reflect.TypeOf((*MockIAMAPI)(nil).TagUser), varargs...)
	return &MockIAMAPITagUserCall{Call: call}
}

// MockIAMAPITagUserCall wrap *gomock.Call
type MockIAMAPITagUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIAMAPITagUserCall) Return(arg0 *iam.TagUserOutput, arg1 error) *MockIAMAPITagUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIAMAPITagUserCall) Do(f func(context.Context, *iam.TagUserInput, ...func(*iam.Options)) (*iam.TagUserOutput, error)) *MockIAMAPITagUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIAMAPITagUserCall) DoAndReturn(f func(context.Context, *iam.TagUserInput, ...func(*iam.Options)) (*iam.TagUserOutput, error)) *MockIAMAPITagUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
