// Copyright (c) 2025 OpenBao a Series of LF Projects, LLC
// SPDX-License-Identifier: MPL-2.0

// Code generated by ./gen.sh. DO NOT EDIT.

package partitions

var data = map[string]string{
	"aws":        "us-east-1",
	"aws-cn":     "cn-northwest-1",
	"aws-us-gov": "us-gov-west-1",
	"aws-iso":    "us-iso-east-1",
	"aws-iso-b":  "us-isob-east-1",
	"aws-iso-e":  "eu-isoe-west-1",
	"aws-iso-f":  "us-isof-south-1",
}
